name: C-Local picasso KSU kernel build
on:
  workflow_dispatch:
  push:
    branches: ["c-local-ksu*"]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential bc bison flex ccache curl git libssl-dev libelf-dev \
            wget xz-utils python2 python3 device-tree-compiler \
            clang-13 lld-13 binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
      - name: build
        run: sed -i 's/\r$//' build-kernel.sh && OUT_ROOT=~/kout bash ./build-kernel.sh
      - uses: actions/upload-artifact@v4
        with:
          name: picasso-kernel
          path: |
            ~/kout/Image
            ~/kout/Image.gz-dtb
            ~/kout/Image.buildinfo
            ~/kout/last-build.log
          retention-days: 30
